version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./backend/data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=mongodb://user:pass@mongodb:27017
    volumes:
      - ./backend/src:/usr/src/app/src
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - backend
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge